theme = "ayu_evolve"

[editor]
mouse= false
bufferline="multiple" #in other words enable multiple tabs functionality
[editor.soft-wrap]
enable = true


[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.normal.g]
a = "code_action" # Maps `ga` to show possible code actions

# Invert `j` and `k` in view mode
[keys.normal.z]
j = "scroll_up"
k = "scroll_down"

# Create a new minor mode bound to `+`
[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"

[keys.normal]
y = "yank_joined_to_clipboard"
C-n = ":bnext"  # Move to the next buffer
C-p = ":bprev"  # Move to the previous buffer
C-w = ":buffer-close"  # Close the current buffer
C-y = "redo"
C-d = ["move_prev_word_start", "move_next_word_end", "search_selection", "extend_search_next"]
C-s = ":write" 
# Move line up and down
"A-j" = [ "keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down" ]
"A-k" = [ "keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection" ]

# select mode multiple occurance
[keys.select]
# if already in select mode, just add new selection at next occurrence
"C-d" = ["search_selection", "extend_search_next"]
# Move lines down




#insert mode key bindings
[keys.insert]
C-s = ":write"  # Remap Alt + s to save (write) the file in insert mode
# Move line up down
"A-j" = [ "keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down" ]
"A-k" = [ "keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection" ]
# cursor in helix
[editor.cursor-shape]
insert = "bar"
normal = "block"

# rotate from the buffers
